#!/bin/bash


Filename=`basename $0`

echo "This is script \"$Filename\" of Major Lab 1"

Files=`ls`


	if [ -f  "greetings.c" ]
	then
		rm greetings.c
		doit=1
	else
		doit1=0
	fi


	if [ -f "gr" ]
	then
		rm gr
		doit2=1
	else
		doit2=0
	fi


if [ $doit1 = 1 ] || [  $doit2 = 1 ]
then
	echo "cleaning done"

else
echo "nothing to clean"
fi
